source("src/lib.R")
print("Preparing data. This might take a second...")
source("src/config.R")
source("src/clean_data.R")
source("src/variables.R")
source("src/mutual_information.R")
source("src/data.R")
source("src/count_entries_lookback.R")
source("src/distribution_with_without_activity.R")
source("src/geo.R")
source("src/activity_dependencies.R")
